---

- name: Encrypt the haproxy pem file
  ansible.builtin.shell:
    cmd: "ansible-vault encrypt --vault-id tls-materials@/tmp/vault-tls-materials {{ lookup('env', 'HOME') }}/wildcard-tls-materials/{{ lookup('pipe', 'date +%Y-%m')}}/generic/_.{{ dns_domain }}-combined.pem"
    executable: /bin/bash
  delegate_to: localhost
  connection: local

- name: Encrypt the wildcard key
  ansible.builtin.shell:
    cmd: "ansible-vault encrypt --vault-id tls-materials@/tmp/vault-tls-materials {{ lookup('env', 'HOME') }}/wildcard-tls-materials/{{ lookup('pipe', 'date +%Y-%m')}}/generic/_.{{ dns_domain }}.key"
    executable: /bin/bash
  delegate_to: localhost
  connection: local

- name: Copy the wildcard PFX bundle to a temporary location
  fetch:
    src: "{{ ansible_user_info.home }}/.lego/certificates/_.{{ dns_domain }}.pfx"
    dest: "{{ lookup('env', 'HOME') }}/wildcard-tls-materials/{{ lookup('pipe', 'date +%Y-%m')}}/generic/"
    flat: true

- name: Encrypt the wildcard PFX bundle
  ansible.builtin.shell:
    cmd: "ansible-vault encrypt --vault-id tls-materials@/tmp/vault-tls-materials {{ lookup('env', 'HOME') }}/wildcard-tls-materials/{{ lookup('pipe', 'date +%Y-%m')}}/generic/_.{{ dns_domain }}.pfx"
    executable: /bin/bash
  delegate_to: localhost
  connection: local

- name: Add the new keys to Git
  ansible.builtin.command:
    cmd: "git add ."
    chdir: "{{ lookup('env', 'HOME') }}/wildcard-tls-materials"
  delegate_to: localhost
  connection: local

- name: Create a new Git commit with the new materials
  ansible.builtin.command:
    cmd: "git commit -m'Updated keys from {{ lookup('pipe', 'date +%Y-%m')}} via Ansible'"
    chdir: "{{ lookup('env', 'HOME') }}/wildcard-tls-materials"
  delegate_to: localhost
  connection: local

- name: Push the Git repository
  ansible.builtin.shell:
    cmd: 'GIT_SSH_COMMAND="ssh -i /tmp/private_material_key -o IdentitiesOnly=yes" git push'
    chdir: "{{ lookup('env', 'HOME') }}/wildcard-tls-materials"
  delegate_to: localhost
  connection: local

